-- Marineford TCG kiosk safety guardrails
-- Apply once in the Supabase SQL editor. Existing data is preserved.
-- The admin PIN remains the current 4-digit PIN; it is copied into a bcrypt hash
-- from store_settings.admin_password only when admin_pin_config is not configured.

begin;

create extension if not exists pgcrypto with schema extensions;

-- Keep the columns used by both the kiosk and the web pre-order flow compatible
-- across the older database snapshots.
alter table public.orders add column if not exists phone_number text;
alter table public.orders add column if not exists payment_method text default 'cash';
alter table public.orders add column if not exists mileage_rate numeric;
alter table public.orders add column if not exists channel text default 'kiosk';
alter table public.orders add column if not exists web_quote_code text;
alter table public.orders add column if not exists quote_expires_at timestamptz;
alter table public.orders add column if not exists client_request_id uuid;

alter table public.order_items add column if not exists payment_method text;
alter table public.order_items add column if not exists note text;
alter table public.order_items add column if not exists declared_condition text;
alter table public.order_items add column if not exists declared_defects jsonb not null default '[]'::jsonb;

create index if not exists idx_orders_created_status
  on public.orders(created_at desc, status);
create unique index if not exists idx_orders_client_request_id
  on public.orders(client_request_id)
  where client_request_id is not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.orders'::regclass
      and conname = 'orders_total_price_nonnegative'
  ) then
    alter table public.orders
      add constraint orders_total_price_nonnegative check (total_price >= 0) not valid;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.order_items'::regclass
      and conname = 'order_items_price_nonnegative'
  ) then
    alter table public.order_items
      add constraint order_items_price_nonnegative check (price >= 0) not valid;
  end if;
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.order_items'::regclass
      and conname = 'order_items_quantity_bounded'
  ) then
    alter table public.order_items
      add constraint order_items_quantity_bounded check (quantity between 1 and 999) not valid;
  end if;
end $$;

-- Feature flags provide a remote kill switch without changing the public URL.
create table if not exists public.store_settings (
  id integer primary key,
  admin_password text not null default '',
  mileage_rate numeric not null default 1.2,
  global_rarities jsonb not null default '["N","R","SR","UR","UL","SE","PSE"]'::jsonb,
  feature_flags jsonb not null default '{"public_buyback_enabled":true,"shipping_buyback_enabled":false}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.store_settings add column if not exists feature_flags jsonb;
update public.store_settings
set feature_flags = coalesce(feature_flags, '{"public_buyback_enabled":true,"shipping_buyback_enabled":false}'::jsonb)
where id = 1;
insert into public.store_settings (id)
values (1)
on conflict (id) do nothing;

-- Hashed PIN storage and an audit trail are not readable through the public anon key.
create table if not exists public.admin_pin_config (
  id integer primary key check (id = 1),
  pin_hash text,
  failed_attempts integer not null default 0,
  locked_until timestamptz,
  updated_at timestamptz not null default now()
);

insert into public.admin_pin_config (id, pin_hash)
select 1, extensions.crypt(s.admin_password, extensions.gen_salt('bf'))
from public.store_settings s
where s.id = 1
  and s.admin_password ~ '^[0-9]{4}$'
on conflict (id) do nothing;

update public.admin_pin_config c
set pin_hash = extensions.crypt(s.admin_password, extensions.gen_salt('bf')),
    updated_at = now()
from public.store_settings s
where c.id = 1
  and c.pin_hash is null
  and s.id = 1
  and s.admin_password ~ '^[0-9]{4}$';

create table if not exists public.admin_auth_events (
  id bigint generated by default as identity primary key,
  success boolean not null,
  reason text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_admin_auth_events_created_at
  on public.admin_auth_events(created_at desc);

alter table public.admin_pin_config enable row level security;
alter table public.admin_auth_events enable row level security;
revoke all on table public.admin_pin_config from anon, authenticated;
revoke all on table public.admin_auth_events from anon, authenticated;

create or replace function public.verify_admin_pin(input_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_hash text;
  v_attempts integer;
  v_locked_until timestamptz;
  v_next_attempts integer;
begin
  if input_pin is null or input_pin !~ '^[0-9]{4}$' then
    insert into public.admin_auth_events(success, reason) values (false, 'invalid_format');
    return jsonb_build_object('authenticated', false, 'code', 'invalid_pin');
  end if;

  select pin_hash, failed_attempts, locked_until
    into v_hash, v_attempts, v_locked_until
  from public.admin_pin_config
  where id = 1
  for update;

  if v_hash is null then
    insert into public.admin_auth_events(success, reason) values (false, 'not_configured');
    return jsonb_build_object('authenticated', false, 'code', 'not_configured');
  end if;

  if v_locked_until is not null and v_locked_until > now() then
    insert into public.admin_auth_events(success, reason) values (false, 'locked');
    return jsonb_build_object(
      'authenticated', false,
      'code', 'locked',
      'retry_after_seconds', greatest(1, extract(epoch from (v_locked_until - now()))::integer)
    );
  end if;

  if extensions.crypt(input_pin, v_hash) = v_hash then
    update public.admin_pin_config
    set failed_attempts = 0, locked_until = null, updated_at = now()
    where id = 1;
    insert into public.admin_auth_events(success, reason) values (true, 'authenticated');
    return jsonb_build_object('authenticated', true, 'session_ttl_seconds', 28800);
  end if;

  v_next_attempts := coalesce(v_attempts, 0) + 1;
  update public.admin_pin_config
  set failed_attempts = v_next_attempts,
      locked_until = case when v_next_attempts >= 5 then now() + interval '15 minutes' else null end,
      updated_at = now()
  where id = 1;
  insert into public.admin_auth_events(success, reason) values (false, 'invalid_pin');

  if v_next_attempts >= 5 then
    return jsonb_build_object('authenticated', false, 'code', 'locked', 'retry_after_seconds', 900);
  end if;
  return jsonb_build_object('authenticated', false, 'code', 'invalid_pin');
end;
$$;

revoke all on function public.verify_admin_pin(text) from public;
grant execute on function public.verify_admin_pin(text) to anon, authenticated;

-- Server-side total calculation is authoritative after an order item changes.
create or replace function public.recalculate_order_total()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_rate numeric;
  v_total integer;
begin
  v_order_id := coalesce(new.order_id, old.order_id);
  select coalesce(mileage_rate, 1) into v_rate from public.orders where id = v_order_id;
  select coalesce(round(sum(
    case when coalesce(payment_method, 'cash') = 'mileage'
      then price * quantity * v_rate
      else price * quantity
    end
  )), 0)::integer into v_total
  from public.order_items
  where order_id = v_order_id;

  update public.orders set total_price = v_total where id = v_order_id;
  return coalesce(new, old);
end;
$$;

drop trigger if exists order_items_recalculate_order_total on public.order_items;
create trigger order_items_recalculate_order_total
after insert or update or delete on public.order_items
for each row execute function public.recalculate_order_total();

commit;
